openapi: 3.0.0
info:
  title: Auth
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3002/api/v1'
paths:
  /login:
    post:
      summary: login
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  token:
                    type: string
      parameters:
        - schema:
            type: string
            default: application/json
          in: header
          name: Content-Type
          description: ''
          required: true
      security:
        - Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
components:
  schemas: {}
  securitySchemes:
    Token:
      type: apiKey
      in: header
      description: ''
      name: 'Bearer [token]'
